### ISSUE TITLE
Project Load failed in Visual studio 2015

### ISSUE THREAD

**Issue by tejasklodha** [mlowijs/mfrc522-netmf#3]
Hi,

when i tried to load your project then its failed and give below error

Mfrc522Lib\Mfrc522Lib.csproj: The application which this project type is based on was not found. Please try this link for further information: http://go.microsoft.com/fwlink/?LinkID=299083&projecttype=b69e3092-b931-443c-abe7-7e7b65f2a37f

Mfrc522Test\Mfrc522Test.csproj: The application which this project type is based on was not found. Please try this link for further information: http://go.microsoft.com/fwlink/?LinkID=299083&projecttype=b69e3092-b931-443c-abe7-7e7b65f2a37f

I used VS 2015

Tejas Lodha

**Comment by akeilox** [comment]
how did you solve this?

im having the same with VS 2017 community edition
